# GitHub Actions workflow to build Go CLI for Windows and Linux
name: Build Go CLI

on:
  push:
    paths:
      - 'cli/**'
      - '.github/workflows/build-cli.yml'
  pull_request:
    paths:
      - 'cli/**'
      - '.github/workflows/build-cli.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux]
        goarch: [amd64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build CLI (${{ matrix.goos }})
        run: |
          cd cli
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o build/cli-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.goos }}-${{ matrix.goarch }}
          path: cli/build/cli-${{ matrix.goos }}-${{ matrix.goarch }}
